### ISSUE TITLE
NoSuchFieldError: Companion

### ISSUE THREAD

**Issue by suofiya** [2captcha/2captcha-java#1]
![企业微信截图_68c73755-c6d1-4fe4-98f7-3bcc6476c1d8](https://user-images.githubusercontent.com/1456885/88028717-9b8efd00-cb6b-11ea-97b9-9bc5bbc4c54c.png)

**Comment by 2captcha** [comment]
@suofiya It mostly looks like a dependency issue and I think it is caused by different versions of okhttp3 required by twocaptcha and some other modules in your code.
Unfortunately I can not reproduce the issue as the info your screenshot is not enough to do that.
